spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/premission?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
logging:
  config:
    classpath: logback.xml